/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 669001ac95f7956b3946b7365c245018)
interface __BaseEnv_Env {
	AI: Ai;
	ASSETS: Fetcher;
	PUBLIC_SITE_URL: "https://zhuodashuai.github.io/vocab/";
	GITHUB_OWNER: "zhuodashuai";
	GITHUB_OWNER_ID: "156042078";
	GITHUB_REPOSITORY: "zhuodashuai.github.io";
	GITHUB_REPOSITORY_ID: "1309360291";
	GITHUB_BRANCH: "main";
	GITHUB_WORDBOOK_PATH: "vocab/data/owner-wordbook.json";
	AI_PROVIDER: "cloudflare";
	ENABLE_FREE_ATTRIBUTION_LOOKUP: "true";
	CLOUDFLARE_AI_MODEL: "@cf/zai-org/glm-4.7-flash";
	CLOUDFLARE_AI_RETRY_MODEL: "@cf/google/gemma-4-26b-a4b-it";
	CLOUDFLARE_RESCUE_MODEL: "@cf/openai/gpt-oss-120b";
	OWNER_CONTROL: DurableObjectNamespace<import("./src/index").OwnerControl>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OwnerControl";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "GITHUB_OWNER" | "GITHUB_OWNER_ID" | "GITHUB_REPOSITORY" | "GITHUB_REPOSITORY_ID" | "GITHUB_BRANCH" | "GITHUB_WORDBOOK_PATH" | "AI_PROVIDER" | "ENABLE_FREE_ATTRIBUTION_LOOKUP" | "CLOUDFLARE_AI_MODEL" | "CLOUDFLARE_AI_RETRY_MODEL" | "CLOUDFLARE_RESCUE_MODEL">> {}
}
