import fs from 'node:fs';
const plan=JSON.parse(fs.readFileSync(new URL('plan.json',import.meta.url),'utf8'));
const map=JSON.parse(fs.readFileSync(new URL('map.json',import.meta.url),'utf8'));
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
for(const option of plan.options){
 const categoryUSD={},statusUSD={};
 for(const day of option.itinerary){
  day.totalGroupUSD=round(day.items.reduce((s,item)=>s+item.amountGroupUSD,0));
  day.perPersonUSD=round(day.totalGroupUSD/plan.party);
  for(const item of day.items){
   if(!Number.isFinite(item.amountGroupUSD)||item.amountGroupUSD<0)throw Error('Invalid amount: '+item.label);
   categoryUSD[item.category]=round((categoryUSD[item.category]||0)+item.amountGroupUSD);
   statusUSD[item.status]=round((statusUSD[item.status]||0)+item.amountGroupUSD);
  }
 }
 const totals=option.totals;
 totals.categoryUSD=categoryUSD;totals.statusUSD=statusUSD;
 totals.dailySubtotalGroupUSD=round(option.itinerary.reduce((s,d)=>s+d.totalGroupUSD,0));
 totals.plannedGroupUSD=round(totals.dailySubtotalGroupUSD+totals.insuranceGearLaundryAllowanceGroupUSD+totals.contingencyGroupUSD);
 totals.plannedPerPersonUSD=round(totals.plannedGroupUSD/plan.party);
 totals.overTargetPerPersonUSD=round(totals.plannedPerPersonUSD-plan.budgetTargetPerPersonUSD);
}
const primary=plan.options.find(o=>o.id===plan.primaryOption);
plan.days=primary.itinerary;plan.totals=primary.totals;
fs.writeFileSync(new URL('data.js',import.meta.url),'// Generated by node build.mjs. Edit plan.json or map.json, then rebuild.\nwindow.WEST_TRAVEL = '+JSON.stringify({plan,...map,evidence:'assets/frontier-phl-sfo-dec8-quote.png'})+';\n');
console.log('Updated data.js: '+plan.options.map(o=>o.name+' '+o.totals.plannedPerPersonUSD).join(' | '));
