/* Actual-date comparisons. Prices are quotes, not reserved inventory. */
(()=>{
 const P=window.WEST_TRAVEL.plan,C=P.comparisons,Q=C.calculator;
 const root=document.getElementById('price-comparison');if(!root)return;
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const round=n=>Math.round(n*100+1e-7)/100;
 const usd=n=>n==null?'总价待核':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
 const a=(url,t)=>url?`<a href="${e(url)}" target="_blank" rel="noopener">${e(t)}</a>`:e(t);
 const tag=(yes)=>yes?'<span class="compare-tag">推荐组合</span>':'';
 const status=r=>({quote:'日期实选报价',published:'官方票价计算',list:'列表／产品价，未到最终页',estimate:'估算／待核',unavailable:'无可订结果'}[r.status]||'待核');
 const locationReview=g=>{const l=g.locationReview;if(!l)return '';return `<div class="location-review"><h5>${e(l.title)}</h5><p>${e(l.summary)}</p><details><summary>查看街区比较、夜归路线与依据</summary><div class="location-area-grid">${l.areas.map(x=>`<article><strong>${e(x.name)}</strong><p>${e(x.reason)}</p>${a(x.url,'位置依据')}</article>`).join('')}</div><ul>${l.practical.map(x=>`<li>${e(x)}</li>`).join('')}</ul><p class="small">依据：${l.sources.map(x=>a(x.url,x.name)).join(' · ')}。未导出同尺度街区犯罪率，因此不作安全数值排名；具体酒店接点与未来时刻仍须确认。</p></details></div>`;};
 const disabledHotel=r=>r.totalUSD==null||r.status==='estimate'||r.id==='elCortezCabanaPetite';
 const composition=r=>{
  if(r.totalUSD==null)return '最终税费／库存未核';
  if(r.baseUSD==null)return '渠道已列含税费总额，未拆分';
  if(r.taxFeeCombinedUSD!=null)return `房费${usd(r.baseUSD)}＋合并税费${usd(r.taxFeeCombinedUSD)}`;
  if(r.taxUSD==null)return `已显示基础价${usd(r.baseUSD)}；最终税费未核`;
  return `房费${usd(r.baseUSD)}＋税${usd(r.taxUSD)}${r.feeUSD?`＋必付费${usd(r.feeUSD)}`:''}`;
 };
 root.innerHTML=`<div class="compare-intro"><h2>先比较和选择，再计算</h2><p>2026/12/8–31，两位成人。每个城市／航段按同日期价格从低到高排列；已含税及列明必付费，未知总价放最后。官网与更便宜公开渠道并列，来源、条件和衔接写在同一行。</p><p class="small">核价日2026/10/7；未预订。推荐组合保留12日下午到蒙特雷，13、14两天完整海岸白天，黄石15–20、Max21–23不动。酒店押金只留信用额度，不重复计成支出。</p><nav class="compare-nav"><a href="#compare-hotels">①酒店</a><a href="#compare-flights">②机票</a><a href="#compare-ground">③车费</a><a href="#compare-calculate">④按选择重算</a></nav></div>
 <div id="compare-hotels"><h3>①酒店 · 一间房两人整段总价，由低到高</h3><p class="small">价格不是每人；平均每晚是比较值，不能当每一晚可单独购买的价格。含早餐／不可退／会员条件分别注明。</p>${C.hotelGroups.map(g=>`<section class="compare-group" data-hotel-group="${e(g.id)}"><h4>${e(g.title)} <span>${e(g.dates)} · ${g.nights}晚</span></h4>${locationReview(g)}<div class="table-scroll"><table class="compare-table"><thead><tr><th>选择／酒店与渠道</th><th>整段含税费<br>平均每晚</th><th>房型、街区与条件</th><th>退改、核价来源</th></tr></thead><tbody>${g.rows.map(r=>`<tr class="${r.recommended?'recommend-row':''}"><td><label class="compare-choice"><input type="radio" name="hotel-${e(g.id)}" value="${e(r.id)}" aria-label="${e(g.title+' '+r.name)}" ${r.recommended?'checked':''} ${disabledHotel(r)?'disabled':''}><strong>${e(r.name)}</strong></label>${tag(r.recommended)}${r.conditional?'<span class="compare-tag conditional">有优惠条件</span>':''}</td><td class="compare-price"><strong>${usd(r.totalUSD)}</strong><br>${r.averageUSD!=null?usd(r.averageUSD)+'/晚':'不进入计算'}<small>${e(composition(r))}</small></td><td>${e(r.room)}<small>${e(r.location)}</small><small>${e(r.caveat)}</small>${r.mapURL?`<small>${a(r.mapURL,'看酒店准确位置')}</small>`:''}</td><td>${e(r.cancel)}<small>${a(r.entrySourceURL||r.sourceURL,r.entrySourceURL?'从公开引流入口查同价':'查看报价渠道')} · ${status(r)}</small></td></tr>`).join('')}</tbody></table></div><p class="small">${e(g.note)}</p></section>`).join('')}</div>
 <div id="compare-flights" class="compare-block"><h3>②机票 · 同航段每人含税价，由低到高</h3><p class="small">表中两人总额不是往返。低价但赶不上黄石或Max的班次照列，明确排除；灰色选项不参与计算。随身箱与托运分开。</p>${C.flightGroups.map((g,j)=>`<section class="compare-group"><h4>${e(g.title)}</h4><div class="table-scroll"><table class="compare-table flights-compare"><thead><tr><th>选择／航班票种</th><th>每人／两人</th><th>当地时间、行李</th><th>衔接判断与来源</th></tr></thead><tbody>${g.rows.map(r=>`<tr class="${r.recommended?'recommend-row':''}"><td><label class="compare-choice"><input type="radio" name="flight-${j}" value="${e(r.id)}" aria-label="${e(g.title+' '+r.name)}" ${r.recommended?'checked':''} ${r.status!=='quote'||r.canChoose===false?'disabled':''}><strong>${e(r.name)}</strong></label>${tag(r.recommended)}</td><td class="compare-price"><strong>${usd(r.perPersonUSD)}/人</strong><br>${usd(r.totalUSD)}/两人<small>${status(r)}</small></td><td>${e(r.time)}<small>${e(r.bags)}</small></td><td>${e(r.decision)}<small>${a(r.sourceURL,'航司官网')}</small></td></tr>`).join('')}</tbody></table></div><p class="small">${e(g.note)}</p></section>`).join('')}<p class="small">Southwest三段基础票含随身箱；United Basic只含个人物品，冬季推荐Economy。托运另外选择：本次三段SW首件$45/航段、UA首件$50；一只共享箱四段共$185两人。退改需核所选票种条款，不默认基础票可退；会员／持卡优惠不默认减免。</p></div>
 <div id="compare-ground" class="compare-block"><h3>③车费 · 分段比较，两人金额由低到高</h3><p class="small">每个小表注明单程或每日；不同城市的日票不能相互替代。机票在车费表里只作巴士比较，计算时不会重复加。</p>${C.groundGroups.map(g=>`<section class="compare-group"><h4>${e(g.title)}</h4><div class="table-scroll"><table class="compare-table ground-compare"><thead><tr><th>方案</th><th>两人／每人</th><th>时刻、包含内容</th><th>选择判断与来源</th></tr></thead><tbody>${g.rows.map(r=>`<tr><td><strong>${e(r.name)}</strong></td><td class="compare-price"><strong>${usd(r.totalUSD)}</strong><br>${r.perPersonUSD!=null?usd(r.perPersonUSD)+'/人':'不进入计算'}<small>${status(r)}</small></td><td>${e(r.time)}</td><td>${e(r.decision)}${r.sourceURL?`<small>${a(r.sourceURL,'运营方官网')}</small>`:''}</td></tr>`).join('')}</tbody></table></div><p class="small">${e(g.note)}</p></section>`).join('')}</div>
 <div id="compare-calculate" class="compare-block"><h3>④确认所选组合，再重算所列费用</h3><p>上方圆点可换酒店和航班。海岸交通、餐费和Max的两种报价在这里选；点按钮后显示合计。没有核价的租车不自动进入总额。</p><div class="compare-form"><label>12日去蒙特雷<select id="coast-out">${Q.coastOutChoices.map(r=>`<option value="${r.id}">${e(r.name)} · ${usd(r.totalUSD)}/两人</option>`).join('')}</select></label><label>14日晚返SFO<select id="coast-back">${Q.coastBackChoices.map(r=>`<option value="${r.id}">${e(r.name)} · ${usd(r.totalUSD)}/两人</option>`).join('')}</select></label><label>MaxTour三日团<select id="compare-max"><option value="official">官网本次含羚羊／纪念碑费用 $838.49/人</option><option value="user">你提供全包 $620/人 · 对应订单待核</option></select></label><label>扣除团内餐后的餐饮预留<select id="compare-food"><option value="60">净预留16×$60=$960/人</option><option value="45">自己安排简餐16×$45=$720/人</option></select></label><label>SF机场两次移动的Muni转乘<select id="compare-sf-transfer"><option value="discount">每人同卡／设备两小时内跨运营商换乘 · 已按折扣算</option><option value="full">未享转乘折扣 · 8／12各加两人单程$5.70，Flix12日除外</option></select></label><label>额外托运行李<select id="compare-bags"><option value="0">不托运 · 推荐随身箱机票已选</option><option value="185">共享一件，四段两人共$185</option><option value="370">每人一件，四段两人共$370</option></select></label></div><div class="controls"><button type="button" id="recalculate">按所选报价重算</button><button type="button" id="copy-price-choice">复制报价选择给队友</button><span id="price-choice-state" class="small" aria-live="polite">已预选推荐组合；合计将在点击后显示。</span></div><div id="comparison-result" aria-live="polite" hidden></div><p class="small">黄石六日含5晚、14餐和导游小费；Max含2晚及部分餐，不重复酒店和已含小费。未含餐饮仍预留。BigSur向导／接送、MossLanding车辆及部分公交末段未全部落实，保留占位。保险、装备、购物、演出、额外景点和突发开销由你们选择后另计。</p></div>`;
 let last=null;
 function calculate(){
  const chosenHotels=C.hotelGroups.map(g=>g.rows.find(r=>r.id===root.querySelector(`input[name="hotel-${g.id}"]:checked`).value));
  const chosenFlights=C.flightGroups.map((g,j)=>g.rows.find(r=>r.id===root.querySelector(`input[name="flight-${j}"]:checked`).value));
  const out=Q.coastOutChoices.find(r=>r.id===document.getElementById('coast-out').value),back=Q.coastBackChoices.find(r=>r.id===document.getElementById('coast-back').value);
  const categories={...Q.otherCategoriesGroupUSD};categories['酒店']=round(chosenHotels.reduce((s,r)=>s+r.totalUSD,0));categories['机票']=round(chosenFlights.reduce((s,r)=>s+r.totalUSD,0));categories['地面交通']=round(Q.groundBaseGroupUSD-Q.coastOutBaseGroupUSD-Q.coastBackBaseGroupUSD+out.totalUSD+back.totalUSD);
  const sfTransferFull=document.getElementById('compare-sf-transfer').value==='full';if(sfTransferFull)categories['地面交通']=round(categories['地面交通']+(out.id==='flix'?5.70:11.40));
  const userMax=document.getElementById('compare-max').value==='user';if(userMax)categories['跟团']=round(categories['跟团']-Q.maxOfficialGroupUSD+Q.maxUserGroupUSD);
  categories['餐饮']=Number(document.getElementById('compare-food').value)*Q.foodDays*2;
  const bags=Number(document.getElementById('compare-bags').value);if(bags)categories['额外托运行李']=bags;
  const total=round(Object.values(categories).reduce((s,v)=>s+v,0));const result=document.getElementById('comparison-result');result.hidden=false;
  result.innerHTML=`<h4>所列项目小计 · ${usd(round(total/2))}/人，${usd(total)}/两人</h4><p class="small">按上方实选报价＋官方票价＋明确占位计算；不是已订全包价。${userMax?'采用你提供的Max$620全包，对应日期订单仍待核。':''}</p><div class="table-scroll"><table class="compare-table result-table"><thead><tr><th>费用</th><th>两人合计</th><th>每人约</th></tr></thead><tbody>${Object.entries(categories).map(([k,v])=>`<tr><td>${e(k)}</td><td>${usd(v)}</td><td>${usd(round(v/2))}</td></tr>`).join('')}<tr><th>所列合计</th><th>${usd(total)}</th><th>${usd(round(total/2))}</th></tr></tbody></table></div><p class="small">${chosenHotels.map(r=>e(r.name)).join('；')}。海岸去程：${e(out.name)}；返程：${e(back.name)}。SF转乘：${sfTransferFull?'按普通单程补费':'按同媒介两小时跨运营商折扣'}。${out.id==='flix'?'12日18:08到Monterey，12日下午游玩减少。':''}</p><p class="small">${chosenHotels.some(r=>r.conditional)?'含有邮件／会员条件价，须本人确认愿意满足条件。 ':''}${chosenHotels.some(r=>/RunOfHouse|Run Of House/.test(r.room))?'含入住时分配房型，床型／无烟不保证。 ':''}${chosenFlights.some(r=>r.id==='bzn-ua')?'UA Basic没有大随身箱；如果另买行李，要加对应航司费用，不能默认免费。 ':''}SF机场末段按每人同卡／设备两小时内BART↔Muni自动折扣；不符合时可切换普通单程费用，实体新卡和银行费用另按实际。换酒店后的末段路线尚未逐家重核，车费暂沿用推荐路线，不保证新地址同价。每人分项四舍五入可能与合计差1–2美分；两人总额为算账依据。</p>`;
  last={categories,total,chosenHotels,chosenFlights,out,back,userMax,sfTransferFull};document.getElementById('price-choice-state').textContent='已按当前选择计算。';
  window.dispatchEvent(new CustomEvent('west-price-calculated',{detail:{totalGroupUSD:total}}));return last;
 }
 document.getElementById('recalculate').addEventListener('click',calculate);
 root.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',()=>{last=null;document.getElementById('comparison-result').hidden=true;document.getElementById('price-choice-state').textContent='选择已变化，请重新点击计算。';}));
 document.getElementById('copy-price-choice').addEventListener('click',async()=>{
  const r=last||calculate();const text=`美西同日期报价选择（2026/10/7核，未预订）：\n${r.chosenHotels.map(x=>`${x.name} ${x.nights}晚／间 ${usd(x.totalUSD)}，${x.cancel}`).join('\n')}\n${r.chosenFlights.map(x=>`${x.name} ${usd(x.perPersonUSD)}/人 ${x.time}，${x.bags}`).join('\n')}\n${r.out.name} ${usd(r.out.totalUSD)}/两人；${r.back.name} ${usd(r.back.totalUSD)}/两人。\n所列费用${usd(r.total)}/两人，${usd(round(r.total/2))}/人；包括标明待核占位。${r.userMax?'Max620为用户全包报价，待订单对应。':''}\nhttps://zhuodashuai.github.io/travel/west-2026/prices.html?v=sf-location-6`;
  try{await navigator.clipboard.writeText(text);document.getElementById('price-choice-state').textContent='已复制，可与页面链接一起发给队友。';}catch{document.getElementById('price-choice-state').textContent='浏览器限制复制，可直接把页面链接发给队友。';}
 });
})();
